export const PLANET_NAMES_ONE = [
  'Solaris',
  'Kepler',
  'Pegasi',
  'Virginis',
  'Gliese',
  'Qatar',
  'Trappist',
  'Eridani',
  'HR',
  'Upsilon',
  'Mu Arae',
  'Pi Mensae',
  'HD',
  '23 Librae',
  'Cetus',
  'Hercules',
  'Circinus',
  'Hydra',
  'Eridanus',
  'Pictor',
  'Pisces',
  'Leo',
  'Rho Coronae Borealis',
  'HD',
  'HD',
  'HD',
  'HD',
  'WASP-',
  'HAT-P-',
  'NN Serpentis',
  'OGLE-',
  'Kepler',
  'Kepler',
  'Kepler',
  'Kepler',
  'Kepler',
  'Kepler',
  'Kepler',
  'Kepler',
  'Kepler',
  'Kepler',
  'Kepler',
  'Kepler',
  'Kepler',
  'Kepler',
  'Kepler',
  'Kepler',
  'Kepler',
  'Kepler',
  'Kepler',
  'Kepler',
  'Kepler',
  'Kepler',
  'Kepler',
  'Kepler',
  'Kepler',
  'Kepler',
  'Kepler',
  'Kepler',
  'Kepler',
  'Kepler',
  'Kepler',
  'Kepler',
  'Kepler',
  '55 Cancri',
  'YZ Ceti',
  'Tiān Yǐ, Celestial Great One',
  '庶子 (Shù Zǐ, Son of Concubine)',
  'آخِرُ ٱلْنََهْر (Unknown System)',
  'الْزُّبَانَى (Unknown System)',
  'عرجة النهر (Curse of the River)',
  'Kapteyns Star',
  'Lillers Star',
  'Zealey-Lee Supernova',
];

export const TECH_LEVELS = [
  'Pre-agricultural',
  'Agricultural',
  'Medieval',
  'Renaissance',
  'Early Industrial',
  'Industrial',
  'Post-Industrial',
  'Hi-Tech',
];

export const POLITICAL_SYSTEMS = {
  anarchy: 'Anarchy',
  capitalistState: 'Capitalist State',
  communistState: 'Communist State',
  confederacy: 'Confederacy',
  corporateState: 'Corporate State',
  cyberneticState: 'Cybernetic State',
  democracy: 'Democracy',
  dictatorship: 'Dictatorship',
  fascistState: 'Fascist State',
  feudalState: 'Feudal State',
  militaryState: 'Military State',
  monarchy: 'Monarchy',
  pacifistState: 'Pacifist State',
  socialistState: 'Socialist State',
  stateOfSatori: 'State of Satori',
  technocracy: 'Technocracy',
  theocracy: 'Theocracy',
};

export function randomRange(min, max) {
  return Math.random() * (max - min) + min;
}

export const NEWS = [
  'This planet is currently starving',
  'This planet is currently thriving under a stable economy',
  'This planet is suffering from a global outbreak of influenza',
];

export const RESOURCE_DEFINITIONS = {
  Water: {
    min: 10,
    max: 20,
    politicalSystem: {
      communismState: 1,
      monarchy: 3,
    },
    techLevel: 1,
  },
  Furs: {
    min: 10,
    max: 20,
    politicalSystem: {
      communismState: 1,
      monarchy: 3,
    },
    techLevel: 1,
  },
  Food: {
    min: 10,
    max: 20,
    politicalSystem: {
      communismState: 1,
      monarchy: 3,
    },
    techLevel: 1,
  },
  Ore: {
    min: 10,
    max: 20,
    politicalSystem: {
      communismState: 1,
      monarchy: 3,
    },
    techLevel: 1,
  },
  Games: {
    min: 10,
    max: 20,
    politicalSystem: {
      communismState: 1,
      monarchy: 3,
    },
    techLevel: 1,
  },
  Firearms: {
    min: 10,
    max: 20,
    politicalSystem: {
      communismState: 1,
      monarchy: 3,
    },
    techLevel: 1,
  },
  Machines: {
    min: 10,
    max: 20,
    politicalSystem: {
      communismState: 1,
      monarchy: 3,
    },
    techLevel: 1,
  },
  Narcotics: {
    min: 1,
    max: 5,
    politicalSystem: {
      communismState: 1,
      monarchy: 0.5,
    },
    techLevel: 8,
  },
  Robots: {
    min: 1,
    max: 5,
    politicalSystem: {
      communismState: 1,
      monarchy: 0.5,
    },
    techLevel: 8,
  },
};

export const EQUIPMENT = {
  pulseLaser: {
    price: 100,
    sellPrice: 85,
    damage: 10,
  },
  pulseShield: {
    price: 1500,
    sellPrice: 125,
    defense: 100,
  },
};
