export const SHIPS = {
  flea: {
    displayName: 'Flea',
    shipId: 1,
    hullStrength: 10,
    shield: 20,
    fuel: 100,
    cargoContainers: 10,
  },

  gnat: {
    displayName: 'Gnat',
    shipId: 2,
    hullStrength: 10,
    shield: 25,
    fuel: 150,
    cargoContainers: 10,
  },
  firefly: {
    displayName: 'Firefly',
    shipId: 3,
    hullStrength: 50,
    shield: 30,
    fuel: 160,
    cargoContainers: 10,
  },
  mosquito: {
    displayName: 'Mosquito',
    shipId: 4,
    hullStrength: 10,
    shield: 20,
    fuel: 100,
    cargoContainers: 10,
  },
  bumblebee: {
    displayName: 'Bumblebee',
    shipId: 5,
    hullStrength: 10,
    shield: 20,
    fuel: 100,
    cargoContainers: 10,
  },
  beetle: {
    displayName: 'Beetle',
    shipId: 6,
    hullStrength: 10,
    shield: 20,
    fuel: 100,
    cargoContainers: 10,
  },
  hornet: {
    displayName: 'Hornet',
    shipId: 7,
    hullStrength: 10,
    shield: 20,
    fuel: 100,
    cargoContainers: 10,
  },
  grasshopper: {
    displayName: 'Grasshopper',
    shipId: 8,
    hullStrength: 10,
    shield: 20,
    fuel: 100,
    cargoContainers: 10,
  },
  termite: {
    displayName: 'Termite',
    shipId: 9,
    hullStrength: 10,
    shield: 20,
    fuel: 100,
    cargoContainers: 10,
  },
  wasp: {
    displayName: 'Wasp',
    shipId: 10,
    hullStrength: 10,
    shield: 20,
    fuel: 100,
    cargoContainers: 10,
  },
};
