export const SHIPS = [
  {
    displayName: 'Flea',
    shipId: 1,
    hullStrength: 10,
    shield: 20,
    fuel: 100,
    cargoContainers: 8,
  },

  {
    displayName: 'Gnat',
    shipId: 2,
    hullStrength: 20,
    shield: 25,
    fuel: 150,
    cargoContainers: 12,
  },
  {
    displayName: 'Firefly',
    shipId: 3,
    hullStrength: 50,
    shield: 30,
    fuel: 160,
    cargoContainers: 14,
  },
  {
    displayName: 'Mosquito',
    shipId: 4,
    hullStrength: 40,
    shield: 20,
    fuel: 100,
    cargoContainers: 18,
  },
  {
    displayName: 'Bumblebee',
    shipId: 5,
    hullStrength: 80,
    shield: 20,
    fuel: 250,
    cargoContainers: 18,
  },
  {
    displayName: 'Beetle',
    shipId: 6,
    hullStrength: 200,
    shield: 200,
    fuel: 500,
    cargoContainers: 30,
  },
  {
    displayName: 'Hornet',
    shipId: 7,
    hullStrength: 300,
    shield: 220,
    fuel: 2500,
    cargoContainers: 10,
  },
  {
    displayName: 'Grasshopper',
    shipId: 8,
    hullStrength: 250,
    shield: 300,
    fuel: 5000,
    cargoContainers: 15,
  },
  {
    displayName: 'Termite',
    shipId: 9,
    hullStrength: 400,
    shield: 1000,
    fuel: 14000,
    cargoContainers: 600,
  },
  {
    displayName: 'Wasp',
    shipId: 10,
    hullStrength: 375,
    shield: 200,
    fuel: 11500,
    cargoContainers: 16,
  },
];
