export const SHIPS = [
  {
    displayName: 'Flea',
    shipId: 1,
    hullStrength: 10,
    shield: 20,
    fuel: 100,
    cargoContainers: 10,
  },

  {
    displayName: 'Gnat',
    shipId: 2,
    hullStrength: 10,
    shield: 25,
    fuel: 150,
    cargoContainers: 10,
  },
  {
    displayName: 'Firefly',
    shipId: 3,
    hullStrength: 50,
    shield: 30,
    fuel: 160,
    cargoContainers: 10,
  },
  {
    displayName: 'Mosquito',
    shipId: 4,
    hullStrength: 10,
    shield: 20,
    fuel: 100,
    cargoContainers: 10,
  },
  {
    displayName: 'Bumblebee',
    shipId: 5,
    hullStrength: 10,
    shield: 20,
    fuel: 100,
    cargoContainers: 10,
  },
  {
    displayName: 'Beetle',
    shipId: 6,
    hullStrength: 10,
    shield: 20,
    fuel: 100,
    cargoContainers: 10,
  },
  {
    displayName: 'Hornet',
    shipId: 7,
    hullStrength: 10,
    shield: 20,
    fuel: 100,
    cargoContainers: 10,
  },
  {
    displayName: 'Grasshopper',
    shipId: 8,
    hullStrength: 10,
    shield: 20,
    fuel: 100,
    cargoContainers: 10,
  },
  {
    displayName: 'Termite',
    shipId: 9,
    hullStrength: 10,
    shield: 20,
    fuel: 100,
    cargoContainers: 10,
  },
  {
    displayName: 'Wasp',
    shipId: 10,
    hullStrength: 10,
    shield: 20,
    fuel: 100,
    cargoContainers: 10,
  },
];
